env: "dev"
authorization:
    - "app"
    - "internal"
    - "openapi"
ip: "127.0.0.1"
port: "3201"
baseConfig:
  etcdConfig:
    endpoints:
      - "http://127.0.0.1:2379"
    user: "root"
    password: "123456"
    timeout: "300ms"
mysqlConfig:
  host:
    read: "127.0.0.1"
    write: "127.0.0.1"
  port: 3306
  user: "root"
  password: "12345678"
  dbName: "app"
tidbConfig:
  charset: "utf8mb4"
  database: "app"
  host: "127.0.0.1:3306"
  mysqlConnMaxLifetime: 5
  mysqlIdle: 10
  mysqlMaxConnections: 400
  password: "12345678"
  timeZone: "+8:00"
  user: "root"
redisConfig:
  address: "127.0.0.1:6379"
  password: ""
  dBNo: 0
jaeger: "http://127.0.0.1:14268/api/traces"